 

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME ='ORM_ORDER')
BEGIN
	CREATE TABLE ORM_ORDER
	(
		OrderID int IDENTITY (1,1) NOT NULL,
		StatusID int NULL,
		AddressID int NULL,
		OrderDate date NULL,
		UserID int NULL,
		INSERTEDDATE DATE NULL,
		INSERTBY varchar(50) NULL

	 CONSTRAINT [PK_ORM_ORDER] PRIMARY KEY CLUSTERED 
	(
		[OrderID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME ='ORM_ORDERDETAILS')
BEGIN
	CREATE TABLE ORM_ORDERDETAILS
	(
		OrderDetailID int IDENTITY (1,1) NOT NULL,
		OrderID int NULL,
		ProductID int NULL,
		Quantity INT NULL,
		INSERTEDDATE DATE NULL ,
		INSERTBY varchar(50) NULL
	 CONSTRAINT [PK_ORM_ORDERDETAILS] PRIMARY KEY CLUSTERED 
	(
		[OrderDetailID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME ='ORM_Product')
BEGIN
	CREATE TABLE ORM_Product
	(
		ProductID int IDENTITY (1,1) NOT NULL,
		ProductName varchar(500) NULL,
		weight  int NULL,
		height int NULL ,
		image binary NULL,
		SKU varchar(500) NULL,
		barcode varchar(500) NULL,
		quantity int NULL,
		INSERTEDDATE DATE NULL,
		INSERTBY varchar(50) NULL
	 CONSTRAINT [PK_ORM_Product] PRIMARY KEY CLUSTERED 
	(
		[ProductID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME ='ORM_Address')
BEGIN
	CREATE TABLE ORM_Address
	(
		AddressID int IDENTITY (1,1) NOT NULL,
		AdressLine1 varchar(500) NULL,
		AdressLine2 varchar(500) NULL,
		State varchar(500) NULL,
		ZipCode varchar(500) NULL,
		EmailID varchar(500) NULL,
		Landmark varchar(500) NULL,
		INSERTEDDATE DATE NULL,
		INSERTBY varchar(50) NULL
	-- CONSTRAINT [ORM_Address] PRIMARY KEY CLUSTERED 
	--(
	--	[AddressID] ASC
	--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	--) ON [PRIMARY]
	)
END