IF EXISTS (SELECT 1 FROM SYS.procedures WHERE NAME ='USP_GET_ORDERDETAILS')
DROP PROCEDURE USP_GET_ORDERDETAILS
GO
/*********************************************************
**
**
**
**
**********************************************************/
CREATE PROCEDURE USP_GET_ORDERDETAILS
(
	@USERID INT
)
AS
BEGIN

	IF EXISTS (SELECT 1 FROM LOGIN L 
					INNER JOIN LOGIN_ROLE_USER LRU ON LRU.USERID = L.ID
					INNER JOIN LOGIN_ROLE LR ON LR.LOGINROLEID = LRU.LOGINROLEID
				WHERE LR.ROLENAME ='USER' AND L.ID = @USERID)
	BEGIN

		SELECT R.ORDERID,R.STATUSID,R.ORDERDATE, R.USERID, RB.QUANTITY ORDERQUANTITY,P.ProductName,
				P.weight,P.height,P.image,P.SKU,P.barcode,P.quantity PRODUCTQUANTITY,A.AdressLine1,
				A.AdressLine2,A.State,A.ZipCode,A.EmailID,A.Landmark		
		  FROM ORM_ORDER R WITH (NOLOCK)
			INNER JOIN ORM_ORDERDETAILS RB WITH (NOLOCK) ON RB.OrderID= R.OrderID
			INNER JOIN ORM_Product P WITH (NOLOCK) ON P.ProductID = RB.PRODUCTID
			INNER JOIN ORM_Address A WITH (NOLOCK) ON A.AddressID = R.AddressID
		WHERE R.USERID = @USERID
	END
	ELSE 
	BEGIN
		SELECT R.ORDERID,R.STATUSID,R.ORDERDATE, R.USERID, RB.QUANTITY ORDERQUANTITY,P.ProductName,
				P.weight,P.height,P.image,P.SKU,P.barcode,P.quantity PRODUCTQUANTITY,A.AdressLine1,
				A.AdressLine2,A.State,A.ZipCode,A.EmailID,A.Landmark		
		  FROM ORM_ORDER R WITH (NOLOCK)
			INNER JOIN ORM_ORDERDETAILS RB WITH (NOLOCK) ON RB.OrderID= R.OrderID
			INNER JOIN ORM_Product P WITH (NOLOCK) ON P.ProductID = RB.PRODUCTID
			INNER JOIN ORM_Address A WITH (NOLOCK) ON A.AddressID = R.AddressID
	END


END